### ISSUE TITLE
Horse Charge skill

### ISSUE THREAD

**Issue by Genii-Locorum** [Genii-Locorum/Pendragon#11]
Just adding this in for the next update- when a character equips a horse, it adds the damage in to a Lance on the Combat part of their sheet, but it doesn't add their Charge skill in, so they roll on a 0.

*raised by Ushgarak on BRP forum*

**Comment by jbowtie** [comment]
The Charge skill in the Base Skills compendium has an incorrect Weapon Type of "None"; it needs to be changed to "Charge" for everything to work correctly.

**Comment by Genii-Locorum** [comment]
@jbowtie - thank you, I've updated the base module and pushed a new release out.

Cheers
