### ISSUE TITLE
Horses and Squires

### ISSUE THREAD

**Issue by jbowtie** [Genii-Locorum/Pendragon#12]
**Proposal:** Currently horses and squires are treated as inventory.  I think they should be independent actors linked to a knight, which should require two new actor types (one for supporters, one for horses).

## Squires

Squires can be promoted to knights in their own right (which in a long campaign may develop them into natural allies or enemies of a player's knight) as well as esquires who might depart in the winter phase.

Other types who may use the supporter actor type would be spouses, maidens-in-waiting, etc. The main thing about all these characters is that they are generally linked to other NPCs as family and they track no glory of their own, but they can be promoted to full characters who inherit and then track glory per the usual rules (spouses who become widows, squires who become knights, maidens who inherit, etc). They also age during the winter phase and may have things happen to them which the GM may want to track.

Having supporters as individual actors I think eases the GM burden, even if we don't provide an automated way to promote a supporter for now. We also expect them to be expanded upon in future supplements (two are named in the 6E core book).

## Horses

Horses should be named, and in addition to the stats they have from their breed, have colors, personalities, possible features, an age, rolls to make during the winter phase and things the GM should track. (I mean, they have a whole chapter to themselves in 6E). It is likely they will be further expanded upon in some future supplement.

**Comment by Genii-Locorum** [comment]
### Horses
With the exception of name, I was expecting most of the rest to be covered in the description - but it would be easy to add the other things (age, breed, colour, personality, features, cost) to the horse when owned.  The horse however is intrinsically linked to the knight - as in it calculates the charge damage etc - and so I don't think it works if they are a separate actor.

On the winter rolls these are already made as part of the actor's winter phase., with health, care, degraded status being tracked and the horses automatically being updated (hopefully this reduced the GM burden).

If the rules do change with future releases then happy to revisit this, but in the meantime I will add the extra data points (breed, colour etc) to the item but I don't think this needs an actor type.

### Squires
With the exceptions of tracking glory and possibly a different winter phase, what is there about Squires, Spouses, Retainers etc that differ materially from "Characters" or "NPCs".  I'm just trying to think how best to develop these if we go down the separate actor type route.  I put a separate NPC sheet together mostly to have a smaller sized sheet as a GM may want multiple open at once.

As the supporters may have their own skills etc then I can see the advantages of having them as actors - but could they be NPCs owned by the relevant player.  

I'd welcome your thoughts - I'm open to the new actor type - just thinking the best route.

Cheers

**Comment by Genii-Locorum** [comment]
I've added extra data points for Horse - only available when it's on the actor sheet, but not limited to GM editing.

<img width="414" alt="image" src="https://github.com/user-attachments/assets/8ff0e8d5-eebb-4f32-a7a0-3c245887e9d7">

**Comment by jbowtie** [comment]
Regarding horses, I feel like type and name should be swapped (to match most other NPCs) but otherwise this addresses most of my concerns about horses, I can now write rollable tables/macros to target those fields when generating new ones.

Regarding supporters, in my head I expect them to promote to full characters and/or move between players. So a few of the scenarios I expect to see over the course of a long campaign (I'm going to be running the Great Pendragon Campaign starting at the end of next month):

* A spouse who is widowed may either marry another player's knight or become a character in her own right.
* A player may play as a squire (most likely when the squire is related to their original knight and close to promotion)
* Handmaidens becoming spouses of another player's knight, especially if battle makes her a sudden heiress.

Modelling them as a regular NPC is reasonable at this stage - I guess my developer sensibilities are looking at the named supplements in the core book and expecting some substantial changes in how that works.

**Comment by Genii-Locorum** [comment]
On horses I think we should leave name, type as they are.  Most people I suspect won't name all their horses so it'd end up being "Horse#1", "Horse#2".  This way if they decide to name it then the name will show.  

I agree that I'm expecting some significant changes on the supporters front.  Let me look in to creating a new actor type as you've suggested with an extra "sub-type" field to distinguish squires, from spouses etc.  They may look very similar to NPCs for now.

What I'll then do is allow these supporters to be "dropped" on to a character (if you are the owner or GM) and you'll get a dialog to specify the relationship.  It won't copy the supporter sheet, but will just be a UUID and a relationship - with quick access to the actor sheet.

I'll do this in addition to the current squire, household "items" - can always revisit this later.  I'm away some of this week but will try to get started on it.

I'll post some screenshots for your review as I go along

**Comment by Genii-Locorum** [comment]
Right - followers.  Here's what I've got so far.

Followers look a lot like NPCs except that
1) Their name is in green, not red
2) You can select a follower type - Squire, Family, Retainer - but this is easy to expand 
3) There is a "book" icon on the right hand side near "Move" - toggling that changes the skills etc to a Personal Details tab with info you can input/toggle.

What's missing at the moment that you'd like to see.  Remember the relationship to the character will be set when you drop it on the character - so a follower could be the wife of one Knight and the sister of another Knight.

I'm going to be away for the rest of the week so won't get much else done on this until the weekend

![image](https://github.com/user-attachments/assets/d6b61338-b0b8-4458-af7b-b3a643f0c7b5)
![image](https://github.com/user-attachments/assets/cdc4d8a3-879f-4cad-8639-586e77600936)

**Comment by jbowtie** [comment]
Being able to build the connections is the most useful part to me personally, I'm quite happy with the follower sheet as it stands.

**Comment by Genii-Locorum** [comment]
Evening - sorry it's been a while, family stuff cropped up again.

So..... I was having a play and as a GM I can drag an actor to an actor and it will create a new item "relationship" on the character *(I've not added the functionality to NPCs, but not discounted it yet).   The problem is that it looks like only GMs can drag actors (and I'm not that versed in Foundry to know how to change that to - or sure if I want to).

So would only letting the GM create the relationships work for you?  Alternatively I could let players create relationships but do it by selecting the actor from a drop down list of all actors and followers (I'm thinking to exclude NPCs so as not to let them know who the GM may have up their sleeve).

Would welcome your thoughts on this.

**Comment by jbowtie** [comment]
My understanding is that players would need appropriate permissions on both actors (I use a module called Ownership Viewer which I find very helpful) for this to work.

I think it's fine to ship as-is, many GMs will want to control this anyway and I can look to add something to the instructions once I verify the permissions needed to allow players to manage it themselves.
