### ISSUE TITLE
Minor Biograpohy Tab Issues

### ISSUE THREAD

**Issue by richard2875** [Genii-Locorum/Pendragon#3]
1. "Heraldry" is misspelled as "Hearldry".
2. Probably should have a line for distinguishing characteristics, like the starter set characters.
3. "Events" box should be relabled as "Description" or "Background", since there's already an Events tab.
4. Different tab, but there should probably be a button to add horses under Companions.

Thanks

**Comment by Genii-Locorum** [comment]
Richard,
Thanks for the feedback
1 - sorted - will be in the next release (hopefully imminent)
2 - I'm being a bit dense - where's the distinguishing characteristics?  Is this the "Pick this knight if......" or the "Distinctive Features" or something else?
3 - sorted (changes to Background"
4 - my original idea was that horses would be items, just drag and drop whatever the GM creates, but now added a "+" icon at the top right of the grid to create a new horse.  Again will be in the next release.

**Comment by Genii-Locorum** [comment]
issues 1,3 & 4 now fixed with release of Beta V5.

Will keep this issue open to resolve point 2.

**Comment by richard2875** [comment]
> 2 - I'm being a bit dense - where's the distinguishing characteristics? Is this the "Pick this knight if......" or the "Distinctive Features" or something else?

It's "Distinctive Features". Got my systems mixed up and used the wrong term, sorry.

**Comment by Genii-Locorum** [comment]
No worries - there should be a box for it beneath the "Background" (what was events) section on the "Biography" tab

**Comment by richard2875** [comment]
Ah, I didn't see that at first, thanks. Maybe you could make it more visible though? I think it would fit as another single-line entry, under heraldry.

**Comment by Genii-Locorum** [comment]
Done - it'll be in release 6 (want to give a chance for other stuff to be included).  It'll be on a line after Heraldry.
