### ISSUE TITLE
Add url to system.json

### ISSUE THREAD

**Issue by farling42** [Genii-Locorum/Pendragon#4]
Please set the url in system.json to "https://github.com/Genii-Locorum/Pendragon"

This makes the link appear in Foundry's Game Settings panel, for easier access to your github.

**Comment by Genii-Locorum** [comment]
Thanks and done. It will be out in the next release - which should be within the next week (depends on how many bugs I've managed to introduce) and how quick a hotfix is needed :-)

**Comment by Genii-Locorum** [comment]
Added in release 9
