### ISSUE TITLE
Error trying to read pid which doesn't exist

### ISSUE THREAD

**Issue by farling42** [Genii-Locorum/Pendragon#7]
In the Actor getData routine, it is trying to read the Pendragon,pidFlag.id to see if an item is an Honour passion. This causes the actor sheet to display very few of the items.

In a world converted to the PID-version of Pendragon this generates an error, since "Pendragon" does not exist as a flag on the item.

A simple conditional access would prevent the error.  `Pendragon?.pidFlag.id`

**Comment by Genii-Locorum** [comment]
@farling42 

Thank you - so we are talking changing line 148 in character.mjs to 

if (i.flags.Pendragon?.pidFlag.id === 'i.passion.honour')  

I'm just working on a "GM Roll" and will push this out with the above fix hopefully this week

**Comment by farling42** [comment]
Yes, that would prevent the error.

**Comment by Genii-Locorum** [comment]
Thank you.  The fix is in a V12 (whilst released here) is with beta-testers.  If they are happy then I will push it out properly in Foundry.

Thanks again

**Comment by Genii-Locorum** [comment]
V12 has now been released
